// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANKg7AdGBrUMl38_jcOItSes0rQzblH98',
    appId: '1:971458692788:web:21a61779c5eecd0e9b39e1',
    messagingSenderId: '971458692788',
    projectId: 'chat-app-8260d',
    authDomain: 'chat-app-8260d.firebaseapp.com',
    storageBucket: 'chat-app-8260d.firebasestorage.app',
    measurementId: 'G-B8BH7MRKGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdRh8XdWY8NPuCd9Ag3xnPttZ9BUpFiM',
    appId: '1:971458692788:android:7f653e0db4476a8e9b39e1',
    messagingSenderId: '971458692788',
    projectId: 'chat-app-8260d',
    storageBucket: 'chat-app-8260d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAezoUfbrX7G5g5p0e0LfBqU9qDRrYZ8D0',
    appId: '1:971458692788:ios:f80ae5662b2b2c1c9b39e1',
    messagingSenderId: '971458692788',
    projectId: 'chat-app-8260d',
    storageBucket: 'chat-app-8260d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
